In [1]:
import pandas as pd
import numpy as np

s = pd.Series(np.random.randint(0, 1000, 1000))
s

0      202
1      588
2      824
3      882
4      991
      ...
995    456
996    255
997    939
998    664
999    574
Length: 1000, dtype: int32

In [2]:
%%timeit -n 10

s = pd.Series(np.random.randint(0, 1000, 1000))
for label, value in s.items():
    s.loc[label] = value+2

34.5 ms ± 2.91 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [3]:
%%timeit -n 10

s = pd.Series(np.random.randint(0, 1000, 1000))

s+=2

226 μs ± 86 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [4]:
import pandas as pd

df = pd.DataFrame({
    "A": [1, 2, 3],
    "B": [4, 5, 6],
    "C": [7, 8, 9]
}, 
index=["Row1", "Row2", "Row3"]
)

print(df)
print(df.dtypes)
print(df.index)
print(df.columns)

      A  B  C
Row1  1  4  7
Row2  2  5  8
Row3  3  6  9
A    int64
B    int64
C    int64
dtype: object
Index(['Row1', 'Row2', 'Row3'], dtype='object')
Index(['A', 'B', 'C'], dtype='object')

In [5]:
print("iloc first row:")
print(df.iloc[0])

print("iloc second row, column B:")
print(df.iloc[1, 1])

print("loc row 3:")
print(df.loc["Row3"])

print("loc column A for all rows:")
print(df.loc[:,"A"])

iloc first row:
A    1
B    4
C    7
Name: Row1, dtype: int64
iloc second row, column B:
5
loc row 3:
A    3
B    6
C    9
Name: Row3, dtype: int64
loc column A for all rows:
Row1    1
Row2    2
Row3    3
Name: A, dtype: int64

In [22]:
mask = (df["A"] > 1) & (df["B"]>4)
print(mask)

filtered = df[mask]
print(filtered)

Row1    False
Row2     True
Row3     True
dtype: bool
      A  B  C
Row2  2  5  8
Row3  3  6  9

In [23]:
df["D"] = df["A"] + df["B"]
df["E"] = df["A"] * df["B"]

print(df)

      A  B  C  D   E
Row1  1  4  7  5   4
Row2  2  5  8  7  10
Row3  3  6  9  9  18

In [ ]:
df = pd.DataFrame({
    "Category": ["A", "B", "A", "B", "A"],
    "Value": [5, 10, 15, 20, 25]
})

df

  Category  Value
0        A      5
1        B     10
2        A     15
3        B     20
4        A     25

In [41]:
grouped = df.groupby("Category")
result = grouped.agg({"Value": ["mean", "sum"]})
result

         Value
          mean sum
Category
A         15.0  45
B         15.0  30