In [1]:
import pandas as pd
import numpy as np

s = pd.Series(np.random.randint(0, 1000, 1000))
s

0      309
1      254
2      920
3      770
4      562
      ...
995     60
996    261
997    731
998     30
999    411
Length: 1000, dtype: int32

In [2]:
%%timeit -n 10

s = pd.Series(np.random.randint(0, 1000, 1000))
for label, value in s.items():
    s.loc[label] = value+2

81.8 ms ± 33.6 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [3]:
%%timeit -n 10

s = pd.Series(np.random.randint(0, 1000, 1000))

s+=2

348 μs ± 118 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [4]:
import pandas as pd

df = pd.DataFrame({
    "A": [1, 2, 3],
    "B": [4, 5, 6],
    "C": [7, 8, 9]
}, 
index=["Row1", "Row2", "Row3"]
)

print(df)
print(df.dtypes)
print(df.index)
print(df.columns)

      A  B  C
Row1  1  4  7
Row2  2  5  8
Row3  3  6  9
A    int64
B    int64
C    int64
dtype: object
Index(['Row1', 'Row2', 'Row3'], dtype='object')
Index(['A', 'B', 'C'], dtype='object')

In [5]:
print("iloc first row:")
print(df.iloc[0])

print("iloc second row, column B:")
print(df.iloc[1, 1])

print("loc row 3:")
print(df.loc["Row3"])

print("loc column A for all rows:")
print(df.loc[:,"A"])

iloc first row:
A    1
B    4
C    7
Name: Row1, dtype: int64
iloc second row, column B:
5
loc row 3:
A    3
B    6
C    9
Name: Row3, dtype: int64
loc column A for all rows:
Row1    1
Row2    2
Row3    3
Name: A, dtype: int64

In [6]:
mask = (df["A"] > 1) & (df["B"]>4)
print(mask)

filtered = df[mask]
print(filtered)

Row1    False
Row2     True
Row3     True
dtype: bool
      A  B  C
Row2  2  5  8
Row3  3  6  9

In [7]:
df["D"] = df["A"] + df["B"]
df["E"] = df["A"] * df["B"]

print(df)

      A  B  C  D   E
Row1  1  4  7  5   4
Row2  2  5  8  7  10
Row3  3  6  9  9  18

In [8]:
df = pd.DataFrame({
    "Category": ["A", "B", "A", "B", "A"],
    "Value": [5, 10, 15, 20, 25]
})

df

  Category  Value
0        A      5
1        B     10
2        A     15
3        B     20
4        A     25

In [9]:
grouped = df.groupby("Category")
result = grouped.agg({"Value": ["mean", "sum"]})
result

         Value
          mean sum
Category
A         15.0  45
B         15.0  30

In [14]:
import pandas as pd

df = pd.read_csv("Admission_Predict.csv", index_col=0)
stripped_cols = [x.lower().strip() for x in df.columns]
df.columns = stripped_cols
df.head()

,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit
Serial No.,,,,,,,,
1,337,118,4,4.5,4.5,9.65,1,0.92
2,324,107,4,4.0,4.5,8.87,1,0.76
3,316,104,3,3.0,3.5,8.00,1,0.72
4,322,110,3,3.5,2.5,8.67,1,0.80
5,314,103,2,2.0,3.0,8.21,0,0.65

In [21]:
admit_mask = df['chance of admit'] > 0.7
admit_mask.head()

Serial No.
1     True
2     True
3     True
4     True
5    False
Name: chance of admit, dtype: bool

In [ ]:
df.where(admit_mask).head()

# or just use
# df = df[admit_mask]

,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit
Serial No.,,,,,,,,
1,337.0,118.0,4.0,4.5,4.5,9.65,1.0,0.92
2,324.0,107.0,4.0,4.0,4.5,8.87,1.0,0.76
3,316.0,104.0,3.0,3.0,3.5,8.00,1.0,0.72
4,322.0,110.0,3.0,3.5,2.5,8.67,1.0,0.80
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
df.where(admit_mask).dropna().head()

,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit
Serial No.,,,,,,,,
1,337.0,118.0,4.0,4.5,4.5,9.65,1.0,0.92
2,324.0,107.0,4.0,4.0,4.5,8.87,1.0,0.76
3,316.0,104.0,3.0,3.0,3.5,8.00,1.0,0.72
4,322.0,110.0,3.0,3.5,2.5,8.67,1.0,0.80
6,330.0,115.0,5.0,4.5,3.0,9.34,1.0,0.90

In [ ]:
# Way better method to include where() and dropna()

df[df['chance of admit'] > 0.7].head()

,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit
Serial No.,,,,,,,,
1,337,118,4,4.5,4.5,9.65,1,0.92
2,324,107,4,4.0,4.5,8.87,1,0.76
3,316,104,3,3.0,3.5,8.00,1,0.72
4,322,110,3,3.5,2.5,8.67,1,0.80
6,330,115,5,4.5,3.0,9.34,1,0.90